const KEY="academic_auto_v1";
const blank={schools:[],students:[],classes:[],subjects:[],results:[],exams:[],settings:{lang:"ar",grading:[{min:90,grade:"A+"},{min:80,grade:"A"},{min:70,grade:"B"},{min:60,grade:"C"},{min:50,grade:"D"},{min:40,grade:"E"},{min:0,grade:"F"}],pass:40}};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||blank;
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function id(p){return p+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,6)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function school(){return db.schools[0]||{}}
function find(a,i){return db[a].find(x=>x.id===i)||{}}
function grade(score){for(const g of db.settings.grading)if(score>=g.min)return g.grade;return "F"}
function status(score){return score>=db.settings.pass?"PASS":"FAIL"}
function pct(total,max){return max?+(total/max*100).toFixed(2):0}
function layout(title,body,actions=""){return `<div class="page-title"><div><h1>${title}</h1><span class="muted">تحديث تلقائي وحسابات فورية</span></div><div>${actions}</div></div>${body}`}
function nav(){document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.page)})}
function render(page="dashboard"){nav();const c=document.getElementById("content");({dashboard,schools,students,classes,subjects,results,exams,documents,settings}[page]||dashboard)();}

function dashboard(){let total=db.results.length,pass=db.results.filter(r=>r.status==="PASS").length;document.getElementById("content").innerHTML=layout("لوحة التحكم",`
<div class="grid">
<div class="card stat"><span>المدارس</span><b>${db.schools.length}</b></div>
<div class="card stat"><span>الطلاب</span><b>${db.students.length}</b></div>
<div class="card stat"><span>المواد</span><b>${db.subjects.length}</b></div>
<div class="card stat"><span>النتائج</span><b>${total}</b><small>${total?Math.round(pass/total*100):0}% ناجح</small></div>
</div>
<div class="panel" style="margin-top:18px"><h3>تشغيل سريع</h3><div class="toolbar">
<button class="btn" onclick="render('schools')">إضافة مدرسة</button><button class="btn" onclick="render('students')">إضافة طالب</button><button class="btn" onclick="render('subjects')">إضافة مادة</button><button class="btn" onclick="render('results')">إدخال الدرجات</button><button class="btn" onclick="render('documents')">توليد مستند</button></div>
<div class="notice">النظام مستقل عن أي مدرسة. جميع القوالب تستخدم البيانات المحفوظة، ويمكنك إنشاء عدد غير محدود عمليًا من المدارس والطلاب والنتائج.</div></div>`)}
function schools(){let rows=db.schools.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.session)}</td><td>${esc(s.phone)}</td><td><button class="danger" onclick="del('schools','${s.id}')">حذف</button></td></tr>`).join("");document.getElementById("content").innerHTML=layout("المدارس",`
<div class="panel"><form id="schoolForm" class="formgrid">
<div class="field"><label>اسم المدرسة *</label><input name="name" required></div><div class="field"><label>السنة الدراسية</label><input name="session" value="2026/2027"></div>
<div class="field"><label>المدير</label><input name="principal"></div><div class="field"><label>الهاتف</label><input name="phone"></div>
<div class="field"><label>البريد</label><input name="email"></div><div class="field"><label>العنوان</label><input name="address"></div>
<div class="field"><label>الشعار</label><input name="logo" type="file" accept="image/*"></div><div class="field"><label>اللغة</label><select name="language"><option value="ar">العربية</option><option value="en">English</option></select></div>
<div class="field full"><button class="btn">حفظ المدرسة</button></div></form></div>
<div class="panel tablewrap"><table class="table"><thead><tr><th>المدرسة</th><th>السنة</th><th>الهاتف</th><th></th></tr></thead><tbody>${rows||`<tr><td colspan="4" class="empty">لا توجد مدارس</td></tr>`}</tbody></table></div>`);
document.getElementById("schoolForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),logo="";let file=f.get("logo");if(file&&file.size)logo=await readFile(file);db.schools.push({id:id("SCH"),name:f.get("name"),session:f.get("session"),principal:f.get("principal"),phone:f.get("phone"),email:f.get("email"),address:f.get("address"),logo,language:f.get("language")});save();schools()}}
function readFile(file){return new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function classes(){let rows=db.classes.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(find("schools",x.schoolId).name)}</td><td><button class="danger" onclick="del('classes','${x.id}')">حذف</button></td></tr>`).join("");document.getElementById("content").innerHTML=layout("الصفوف",`<div class="panel"><form id="f" class="formgrid"><div class="field"><label>اسم الصف *</label><input name="name" required></div><div class="field"><label>المدرسة</label><select name="schoolId">${db.schools.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select></div><div class="field full"><button class="btn">حفظ الصف</button></div></form></div><div class="panel tablewrap"><table class="table"><tr><th>الصف</th><th>المدرسة</th><th></th></tr>${rows}</table></div>`);document.getElementById("f").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);db.classes.push({id:id("CLS"),name:f.get("name"),schoolId:f.get("schoolId")});save();classes()}}
function students(){let rows=db.students.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.number)}</td><td>${esc(find("classes",x.classId).name)}</td><td>${esc(find("schools",x.schoolId).name)}</td><td><button class="danger" onclick="del('students','${x.id}')">حذف</button></td></tr>`).join("");document.getElementById("content").innerHTML=layout("الطلاب",`<div class="panel"><form id="f" class="formgrid"><div class="field"><label>اسم الطالب *</label><input name="name" required></div><div class="field"><label>رقم الطالب</label><input name="number"></div><div class="field"><label>المدرسة</label><select name="schoolId" id="ss">${db.schools.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select></div><div class="field"><label>الصف</label><select name="classId">${db.classes.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("")}</select></div><div class="field"><label>ولي الأمر</label><input name="guardian"></div><div class="field"><label>الجنس</label><select name="gender"><option>male</option><option>female</option></select></div><div class="field full"><button class="btn">إضافة الطالب</button></div></form></div><div class="panel tablewrap"><table class="table"><tr><th>الاسم</th><th>الرقم</th><th>الصف</th><th>المدرسة</th><th></th></tr>${rows||`<tr><td colspan="5" class="empty">لا يوجد طلاب</td></tr>`}</table></div>`);document.getElementById("f").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);db.students.push({id:id("STD"),name:f.get("name"),number:f.get("number"),schoolId:f.get("schoolId"),classId:f.get("classId"),guardian:f.get("guardian"),gender:f.get("gender")});save();students()}}
function subjects(){let rows=db.subjects.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.max}</td><td>${x.pass}</td><td><button class="danger" onclick="del('subjects','${x.id}')">حذف</button></td></tr>`).join("");document.getElementById("content").innerHTML=layout("المواد الدراسية",`<div class="panel"><form id="f" class="formgrid"><div class="field"><label>المادة *</label><input name="name" required></div><div class="field"><label>الدرجة العظمى</label><input name="max" type="number" value="100"></div><div class="field"><label>درجة النجاح</label><input name="pass" type="number" value="40"></div><div class="field"><label>المدرسة</label><select name="schoolId">${db.schools.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select></div><div class="field full"><button class="btn">حفظ المادة</button></div></form></div><div class="panel tablewrap"><table class="table"><tr><th>المادة</th><th>العظمى</th><th>النجاح</th><th></th></tr>${rows||`<tr><td colspan="4" class="empty">لا توجد مواد</td></tr>`}</table></div>`);document.getElementById("f").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);db.subjects.push({id:id("SUB"),name:f.get("name"),max:+f.get("max"),pass:+f.get("pass"),schoolId:f.get("schoolId")});save();subjects()}}
function results(){let rows=db.results.map(r=>`<tr><td>${esc(find("students",r.studentId).name)}</td><td>${esc(find("subjects",r.subjectId).name)}</td><td>${r.score}/${r.max}</td><td>${r.percentage}%</td><td>${r.grade}</td><td><span class="badge">${r.status}</span></td><td><button class="danger" onclick="del('results','${r.id}')">حذف</button></td></tr>`).join("");document.getElementById("content").innerHTML=layout("إدخال الدرجات",`<div class="panel"><form id="f" class="formgrid"><div class="field"><label>الطالب *</label><select name="studentId">${db.students.map(s=>`<option value="${s.id}">${esc(s.name)} — ${esc(find("classes",s.classId).name)}</option>`).join("")}</select></div><div class="field"><label>المادة *</label><select name="subjectId">${db.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select></div><div class="field"><label>الدرجة</label><input name="score" type="number" step="0.01" required></div><div class="field full"><button class="btn">حفظ وحساب تلقائي</button></div></form></div><div class="panel tablewrap"><table class="table"><tr><th>الطالب</th><th>المادة</th><th>الدرجة</th><th>%</th><th>التقدير</th><th>الحالة</th><th></th></tr>${rows||`<tr><td colspan="7" class="empty">لا توجد درجات</td></tr>`}</table></div>`);document.getElementById("f").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),s=find("subjects",f.get("subjectId")),score=Math.max(0,Math.min(+f.get("score"),s.max)),p=pct(score,s.max);let old=db.results.find(r=>r.studentId===f.get("studentId")&&r.subjectId===f.get("subjectId"));let obj={id:old?.id||id("RES"),studentId:f.get("studentId"),subjectId:f.get("subjectId"),score,max:s.max,percentage:p,grade:grade(p),status:score>=s.pass?"PASS":"FAIL"};if(old)Object.assign(old,obj);else db.results.push(obj);save();results()}}
function exams(){document.getElementById("content").innerHTML=layout("الاختبارات والامتحانات",`<div class="panel"><form id="f" class="formgrid"><div class="field"><label>عنوان الاختبار</label><input name="title" required></div><div class="field"><label>المادة</label><select name="subjectId">${db.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select></div><div class="field"><label>المدة بالدقائق</label><input name="duration" type="number" value="60"></div><div class="field"><label>عدد الأسئلة</label><input name="questions" type="number" value="20"></div><div class="field full"><button class="btn">إنشاء اختبار</button></div></form></div><div class="panel tablewrap"><table class="table"><tr><th>العنوان</th><th>المادة</th><th>المدة</th><th>الأسئلة</th></tr>${db.exams.map(e=>`<tr><td>${esc(e.title)}</td><td>${esc(find("subjects",e.subjectId).name)}</td><td>${e.duration}</td><td>${e.questions}</td></tr>`).join("")||`<tr><td colspan="4" class="empty">لا توجد اختبارات</td></tr>`}</table></div>`);document.getElementById("f").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);db.exams.push({id:id("EXM"),title:f.get("title"),subjectId:f.get("subjectId"),duration:+f.get("duration"),questions:+f.get("questions")});save();exams()}}
function documents(){document.getElementById("content").innerHTML=layout("مولّد المستندات",`<div class="panel no-print"><div class="toolbar"><label>الطالب <select id="docStudent">${db.students.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select></label><button class="btn" onclick="generateCertificate()">توليد الشهادة</button><button class="btn ghost" onclick="window.print()">طباعة / PDF</button></div></div><div id="docArea" class="empty">اختر طالبًا ثم اضغط «توليد الشهادة».</div>`)}
function generateCertificate(){let st=find("students",document.getElementById("docStudent").value),sc=find("schools",st.schoolId),cl=find("classes",st.classId),rs=db.results.filter(r=>r.studentId===st.id),total=rs.reduce((a,r)=>a+r.score,0),max=rs.reduce((a,r)=>a+r.max,0),average=pct(total,max),pos=position(st.id,st.classId);document.getElementById("docArea").innerHTML=`<div class="certificate"><img class="schoollogo" src="${sc.logo||''}" onerror="this.style.display='none'"><h1>${esc(sc.name||"School")}</h1><p>${esc(sc.address||"")}</p><h2>شهادة نتيجة دراسية</h2><p>تشهد إدارة المدرسة بأن الطالب/ة</p><h2>${esc(st.name)}</h2><p>رقم الطالب: ${esc(st.number||"—")} &nbsp; | &nbsp; الصف: ${esc(cl.name||"—")}</p><table><tr><th>المادة</th><th>الدرجة</th><th>النسبة</th><th>التقدير</th></tr>${rs.map(r=>`<tr><td>${esc(find("subjects",r.subjectId).name)}</td><td>${r.score}/${r.max}</td><td>${r.percentage}%</td><td>${r.grade}</td></tr>`).join("")||`<tr><td colspan="4">لا توجد درجات</td></tr>`}<tr><th>المجموع</th><th>${total}/${max}</th><th>${average}%</th><th>${grade(average)}</th></tr></table><p><strong>النتيجة: ${status(average)}</strong> &nbsp; | &nbsp; الترتيب: ${pos||"—"}</p><p>السنة الدراسية: ${esc(sc.session||"—")}</p><div class="sig"><span>المدير<br><br>____________</span><span>الختم<br><br>____________</span></div></div>`}
function position(studentId,classId){let ids=db.students.filter(s=>s.classId===classId).map(s=>s.id);let arr=ids.map(id=>{let rs=db.results.filter(r=>r.studentId===id);return{id,avg:pct(rs.reduce((a,r)=>a+r.score,0),rs.reduce((a,r)=>a+r.max,0))}}).sort((a,b)=>b.avg-a.avg);let i=arr.findIndex(x=>x.id===studentId);return i<0?null:i+1}
function settings(){document.getElementById("content").innerHTML=layout("الإعدادات",`<div class="panel"><form id="f" class="formgrid"><div class="field"><label>درجة النجاح العامة</label><input name="pass" type="number" value="${db.settings.pass}"></div><div class="field"><label>اللغة</label><select name="lang"><option value="ar">العربية</option><option value="en">English</option></select></div><div class="field full"><p class="muted">التقديرات الافتراضية: A+ 90، A 80، B 70، C 60، D 50، E 40، F أقل من 40.</p><button class="btn">حفظ</button></div></form></div><div class="panel"><button class="danger" onclick="resetData()">مسح جميع البيانات</button></div>`);document.getElementById("f").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);db.settings.pass=+f.get("pass");db.settings.lang=f.get("lang");save();alert("تم الحفظ")}}
function del(type,ident){if(confirm("هل تريد الحذف؟")){db[type]=db[type].filter(x=>x.id!==ident);save();render(type==="schools"?"schools":type)}}
function resetData(){if(confirm("سيتم حذف كل البيانات نهائيًا من هذا المتصفح. متابعة؟")){localStorage.removeItem(KEY);location.reload()}}
function backupData(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:"application/json"}));a.download="academic-backup.json";a.click();URL.revokeObjectURL(a.href)}
document.getElementById("restoreFile").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();location.reload()}catch{alert("ملف غير صالح")}};r.readAsText(f)}
function toggleLang(){alert("النسخة الأساسية عربية RTL. يمكن إضافة واجهة إنجليزية كاملة في المرحلة التالية دون تغيير قاعدة البيانات.")}
render();